data:
  domain:
    xmin: -2
    xmax: 2
    tmin: 0
    tmax: 1
  Nx_u: 51  # Resolution of the solution
  Nx_f: 101
  Nt_f: 101
  N_input: 5000
  type_x: 'exp'
  order_x: 2
  type_t: 'poly_cos'
  tol:
    u0: 0.2
    ut0: 0
    f: 0.6


model:
  m1: 51
  branch1_layers: [51, 100, 100, 100, 100]
  m2: 51
  branch2_layers: [51, 100, 100, 100, 100]
  m3: 225
  branch3_layers: [225, 225, 225, 225, 100]
  trunk_layers: [2, 400, 400, 400, 100]
  act: tanh

train:
  batch_size: 8192
  nIter: 150_000
  save_it: 50_000
  save_error_it: 1000
  # milestones: [5000, 10000, 20000, 40000, 60000, 80000]
  step_size: 500
  base_lr: 0.001
  scheduler_gamma: 0.97
  weight_bcs: 1
  weight_res: 1
  # save_path: debug
  save_name: WaveData-20230707-0
  domain:
    xmin: -1
    xmax: 1
    tmin: 0
    tmax: 1
  Nx: 101  # Resolution of the solution
  Nt: 101
  N_input: 5000  # number of input functions
  P_ic: 101
  P_i: 51


test:
  domain:
    xmin: -1
    xmax: 1
    tmin: 0
    tmax: 1
  Nx: 101  # Resolution of numerical solution and plot
  Nt: 401
  N_test: 100  # number of input samples
  it: 150_000
  domain_ref:
    xmin: -10
    xmax: 10
    tmin: 0
    tmax: 1
  Nx_ref: 2001
  Nt_ref: 401 # =2Nt
  noisy_N: 100
  noise_f: 0.01
  noise_u0: 0.0
  noise_ut0: 0.0